baseURL: https://pmargarido.dev/
languageCode: en-us
title: Pedro Margarido
theme: terminal-resume

params:
  author: Pedro Margarido
  description: Software Engineer - Personal Resume
  email: ptmmmargarido@gmail.com
  
  social:
    github: https://github.com/PTMargarido
    linkedin: https://linkedin.com/in/pedro-margarido

menu:
  main:
    - name: Resume
      url: /#resume
      weight: 1
    - name: Contact
      url: /#contact
      weight: 2